### ISSUE TITLE
Resize hero image and make responsive

### ISSUE THREAD

**Issue by brian-gee** [brian-gee/astro-portfolio#1]
Change the aspect ratio of hero image, and correct sizing to make image responsive.

**Comment by Aathirajan** [comment]
hi can i work on this issue

**Comment by brian-gee** [comment]
Awesome, I have assigned you the issue. Let me know if there is anything I can do to help.

**Comment by Aathirajan** [comment]
cool thanks!

**Comment by Aathirajan** [comment]
bro where is it actually?

**Comment by brian-gee** [comment]
If you look at the hero component within the src folder (src/components) there is an image on the index page. The image being used is within src/assets/bg.jpg. We don't need to change the image, just the tailwindcss styles associated with the div, or picture tag within the src/components/hero.astro file. Let me know if this helps.

**Comment by Aathirajan** [comment]
yeah I found it! Is there any extensions out there for astro files? coz its showing me like a text file!

**Comment by brian-gee** [comment]
There definitely is if you use vscode!
 https://marketplace.visualstudio.com/items?itemName=astro-build.astro-vscode

**Comment by Aathirajan** [comment]
yeah got it. Thanks.

**Comment by Aathirajan** [comment]
Is that okay mate! I'm looking forward to your suggestions

**Comment by Aathirajan** [comment]
brother shall we connect? can you share your Twitter.

**Comment by brian-gee** [comment]
I don't have much social media but I have followed you on github and linkedin!

**Comment by Aathirajan** [comment]
That's Great!
